import type { Metadata } from "next";
import React from "react";
import Navbar from "../components/Navbar";
import Header from "./component/Header";
import Sidebar from "./component/Sidebar";
import RestuarentCard from "./component/RestuarentCard";
import { PRICE, PrismaClient } from "@prisma/client";

export const metadata: Metadata = {
  title: "OpenTable | Search",
  description: "Generated by create next app",
};
interface searchParams{ city?: string, region?: string, price?: PRICE }

const prisma = new PrismaClient()

const restuarentSearch = async(searchParams: searchParams) => {
  const where: any = {}

  if(searchParams.city){
   const location =  {
    name : {
      equals : searchParams.city.toLocaleLowerCase()
    }
   }
   where.location = location
  }
  if(searchParams.region){
    const region =  {
     name : {
       equals : searchParams.region.toLocaleLowerCase()
     }
    }
    where.region = region
   }
   if(searchParams.price){
    const price = {
      equals: searchParams.price
    }
    where.price = price
   }

  const select = {
    id: true,
    name: true,
    main_image: true,
    price: true,
    location: true,
    region: true,
    slug: true,
    reviews: true
  }
  

  return await prisma.restaurant.findMany({
    where,
    select
  })
};
const fetchLocation=()=>{
  return prisma.location.findMany()
}
const fetchRegion=()=>{
  return prisma.region.findMany()
}

const SearchPage = async({ searchParams }: { searchParams: searchParams }) => {
  const restuarents = await restuarentSearch(searchParams)
  const locations  = await fetchLocation()
  const regions  = await fetchRegion()
  return (
    <>
      <Header />
      <div className="flex py-4 m-auto w-2/3 justify-between items-start">
        <Sidebar locations={locations} regions={regions} searchParams={searchParams} />
        <div className="w-5/6">
        {
          restuarents.length ? (
            restuarents.map((restuarent)=>(<RestuarentCard key={restuarent.id} restuarent={restuarent} />))
          ) :(<h2>Restuarent not avaliable</h2>)
        }
          
        </div>
      </div>
    </>
  );
};

export default SearchPage;
